//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventurApp.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventurApp.Culture.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimension1.
        /// </summary>
        internal static string Abmassfeld1 {
            get {
                return ResourceManager.GetString("Abmassfeld1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimension3.
        /// </summary>
        internal static string Abmassfeld2 {
            get {
                return ResourceManager.GetString("Abmassfeld2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimension4.
        /// </summary>
        internal static string Abmassfeld3 {
            get {
                return ResourceManager.GetString("Abmassfeld3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimension2.
        /// </summary>
        internal static string Abmassfeld4 {
            get {
                return ResourceManager.GetString("Abmassfeld4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the serial number.
        /// </summary>
        internal static string Addserialnr {
            get {
                return ResourceManager.GetString("Addserialnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add serial number.
        /// </summary>
        internal static string addSerNR {
            get {
                return ResourceManager.GetString("addSerNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already counted.
        /// </summary>
        internal static string Alreadycounted {
            get {
                return ResourceManager.GetString("Alreadycounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key.
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrive.
        /// </summary>
        internal static string Arrive {
            get {
                return ResourceManager.GetString("Arrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported items.
        /// </summary>
        internal static string Artikel_list {
            get {
                return ResourceManager.GetString("Artikel_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to upload the current inventory list?.
        /// </summary>
        internal static string ask__upload_Aktuel_StoragList {
            get {
                return ResourceManager.GetString("ask_ upload_Aktuel_StoragList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the ongoing counting?.
        /// </summary>
        internal static string Ask_delete_StoragList {
            get {
                return ResourceManager.GetString("Ask_delete_StoragList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to leave the current counting?.
        /// </summary>
        internal static string ask_leave_page_counting {
            get {
                return ResourceManager.GetString("ask_leave_page_counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want share the DataBase ?.
        /// </summary>
        internal static string AskSharefile {
            get {
                return ResourceManager.GetString("AskSharefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of serial numbers does not match the specified quantity. Do you want to adjust the amount?”.
        /// </summary>
        internal static string askToSeriNRAmount {
            get {
                return ResourceManager.GetString("askToSeriNRAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfassen.
        /// </summary>
        internal static string capture {
            get {
                return ResourceManager.GetString("capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capture.
        /// </summary>
        internal static string capture1 {
            get {
                return ResourceManager.GetString("capture1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Storage.
        /// </summary>
        internal static string change_storage {
            get {
                return ResourceManager.GetString("change_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change storage.
        /// </summary>
        internal static string changestorage {
            get {
                return ResourceManager.GetString("changestorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lot capable.
        /// </summary>
        internal static string Chargenfahig {
            get {
                return ResourceManager.GetString("Chargenfahig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your settings or your internet connection.
        /// </summary>
        internal static string checkInternetConnection {
            get {
                return ResourceManager.GetString("checkInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Check your Value!!.
        /// </summary>
        internal static string CheckValue {
            get {
                return ResourceManager.GetString("CheckValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to navigate away from this page?.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit the app?.
        /// </summary>
        internal static string closeapp {
            get {
                return ResourceManager.GetString("closeapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee.
        /// </summary>
        internal static string Committee {
            get {
                return ResourceManager.GetString("Committee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed message.
        /// </summary>
        internal static string Completedmessage {
            get {
                return ResourceManager.GetString("Completedmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Counting.
        /// </summary>
        internal static string continue_counting {
            get {
                return ResourceManager.GetString("continue_counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data will be deleted. Are you sure?.
        /// </summary>
        internal static string delete_counting_dialog_description {
            get {
                return ResourceManager.GetString("delete_counting_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete counting?.
        /// </summary>
        internal static string delete_counting_dialog_title {
            get {
                return ResourceManager.GetString("delete_counting_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the serial numbers?.
        /// </summary>
        internal static string deleteSerialNR {
            get {
                return ResourceManager.GetString("deleteSerialNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description1.
        /// </summary>
        internal static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string DeviceID {
            get {
                return ResourceManager.GetString("DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to exit.
        /// </summary>
        internal static string dontallowleave {
            get {
                return ResourceManager.GetString("dontallowleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have this permission !.
        /// </summary>
        internal static string dontpermission {
            get {
                return ResourceManager.GetString("dontpermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Item List.
        /// </summary>
        internal static string download_item_list {
            get {
                return ResourceManager.GetString("download_item_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string enterpass {
            get {
                return ResourceManager.GetString("enterpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter all Serialnumber!.
        /// </summary>
        internal static string enterserialnumer {
            get {
                return ResourceManager.GetString("enterserialnumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERPall Business Software Gmbh .
        /// </summary>
        internal static string ERPName {
            get {
                return ResourceManager.GetString("ERPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47877 Willich .
        /// </summary>
        internal static string ERPStadtadresse {
            get {
                return ResourceManager.GetString("ERPStadtadresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakob-Kaiser-Str. 7, .
        /// </summary>
        internal static string ERPStradresse {
            get {
                return ResourceManager.GetString("ERPStradresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was not saved successfully!.
        /// </summary>
        internal static string errorexportedDataBase1 {
            get {
                return ResourceManager.GetString("errorexportedDataBase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please fill in all fields!.
        /// </summary>
        internal static string ErrorFilltheFilde {
            get {
                return ResourceManager.GetString("ErrorFilltheFilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was not saved successfully!.
        /// </summary>
        internal static string errorsaveDataBase {
            get {
                return ResourceManager.GetString("errorsaveDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Counting.
        /// </summary>
        internal static string export_counting {
            get {
                return ResourceManager.GetString("export_counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Counting (Offline).
        /// </summary>
        internal static string export_counting_offline {
            get {
                return ResourceManager.GetString("export_counting_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file.
        /// </summary>
        internal static string export_file {
            get {
                return ResourceManager.GetString("export_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file has been successfully exported..
        /// </summary>
        internal static string export_success_dialog_description {
            get {
                return ResourceManager.GetString("export_success_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export finished.
        /// </summary>
        internal static string export_success_dialog_title {
            get {
                return ResourceManager.GetString("export_success_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this file is not DB.
        /// </summary>
        internal static string fileisntDB {
            get {
                return ResourceManager.GetString("fileisntDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Amont.
        /// </summary>
        internal static string Goodamount {
            get {
                return ResourceManager.GetString("Goodamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDCardNr.
        /// </summary>
        internal static string IDCardNr {
            get {
                return ResourceManager.GetString("IDCardNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID-Number.
        /// </summary>
        internal static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Item List.
        /// </summary>
        internal static string import_item_list {
            get {
                return ResourceManager.GetString("import_item_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Item List (Offline).
        /// </summary>
        internal static string import_item_list_offline {
            get {
                return ResourceManager.GetString("import_item_list_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file has been successfully imported..
        /// </summary>
        internal static string import_success_dialog_description1 {
            get {
                return ResourceManager.GetString("import_success_dialog_description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import finished.
        /// </summary>
        internal static string import_success_dialog_title1 {
            get {
                return ResourceManager.GetString("import_success_dialog_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interrupt.
        /// </summary>
        internal static string interrupt {
            get {
                return ResourceManager.GetString("interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory has beed read in:.
        /// </summary>
        internal static string Inventoryread {
            get {
                return ResourceManager.GetString("Inventoryread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted items.
        /// </summary>
        internal static string inventur_list {
            get {
                return ResourceManager.GetString("inventur_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no matching item in the database..
        /// </summary>
        internal static string item_not_found_dialog_description {
            get {
                return ResourceManager.GetString("item_not_found_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        internal static string item_not_found_dialog_title {
            get {
                return ResourceManager.GetString("item_not_found_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items:.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string kzLand {
            get {
                return ResourceManager.GetString("kzLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languge:.
        /// </summary>
        internal static string Languge {
            get {
                return ResourceManager.GetString("Languge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out automatically (seconds).
        /// </summary>
        internal static string Logoutautomatically_seconds_ {
            get {
                return ResourceManager.GetString("Logoutautomatically(seconds)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lot.
        /// </summary>
        internal static string lot {
            get {
                return ResourceManager.GetString("lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot field is required..
        /// </summary>
        internal static string lot_missing_dialog_description {
            get {
                return ResourceManager.GetString("lot_missing_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot missing.
        /// </summary>
        internal static string lot_missing_dialog_title {
            get {
                return ResourceManager.GetString("lot_missing_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        internal static string menge {
            get {
                return ResourceManager.GetString("menge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Value ist 20.
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Counting.
        /// </summary>
        internal static string new_counting {
            get {
                return ResourceManager.GetString("new_counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scan.
        /// </summary>
        internal static string new_scan {
            get {
                return ResourceManager.GetString("new_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New scan.
        /// </summary>
        internal static string newscan {
            get {
                return ResourceManager.GetString("newscan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;To apply the new language  you need to restart the App.&quot;.
        /// </summary>
        internal static string newsetting {
            get {
                return ResourceManager.GetString("newsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storagecode not correct.
        /// </summary>
        internal static string not_valid_storage {
            get {
                return ResourceManager.GetString("not_valid_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid Inventory.
        /// </summary>
        internal static string not_valid_StoregId {
            get {
                return ResourceManager.GetString("not_valid_StoregId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not valid.
        /// </summary>
        internal static string not_valid_user {
            get {
                return ResourceManager.GetString("not_valid_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is not a database file.
        /// </summary>
        internal static string notDBfile {
            get {
                return ResourceManager.GetString("notDBfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number/Occupy.
        /// </summary>
        internal static string Number_occupy {
            get {
                return ResourceManager.GetString("Number_occupy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password , Try again!.
        /// </summary>
        internal static string passwrong {
            get {
                return ResourceManager.GetString("passwrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Inventory !.
        /// </summary>
        internal static string please_select_InventurId {
            get {
                return ResourceManager.GetString("please_select_InventurId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill only Qty1 or Qty2..
        /// </summary>
        internal static string quantity_error_dialog_description {
            get {
                return ResourceManager.GetString("quantity_error_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Error.
        /// </summary>
        internal static string quantity_error_dialog_title {
            get {
                return ResourceManager.GetString("quantity_error_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Qty1 is required.
        /// </summary>
        internal static string quantity_missing_dialog_description {
            get {
                return ResourceManager.GetString("quantity_missing_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity missing.
        /// </summary>
        internal static string quantity_missing_dialog_title {
            get {
                return ResourceManager.GetString("quantity_missing_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to Restore the default settings?.
        /// </summary>
        internal static string RestorAsk {
            get {
                return ResourceManager.GetString("RestorAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        internal static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        internal static string save_file {
            get {
                return ResourceManager.GetString("save_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataBase have been saved successfully!.
        /// </summary>
        internal static string saveDataBase {
            get {
                return ResourceManager.GetString("saveDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) saved successfully.
        /// </summary>
        internal static string saveitemwithserinummer {
            get {
                return ResourceManager.GetString("saveitemwithserinummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the serial numbers?.
        /// </summary>
        internal static string saveSerialNR {
            get {
                return ResourceManager.GetString("saveSerialNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan barcode.
        /// </summary>
        internal static string Scanbarcode {
            get {
                return ResourceManager.GetString("Scanbarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        internal static string select_file {
            get {
                return ResourceManager.GetString("select_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial numbers.
        /// </summary>
        internal static string serial_numbers {
            get {
                return ResourceManager.GetString("serial_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item requires a serial number..
        /// </summary>
        internal static string serials_missing_dialog_description {
            get {
                return ResourceManager.GetString("serials_missing_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serials missing.
        /// </summary>
        internal static string serials_missing_dialog_title {
            get {
                return ResourceManager.GetString("serials_missing_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serial capable.
        /// </summary>
        internal static string seriennummerfähig {
            get {
                return ResourceManager.GetString("seriennummerfähig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share file.
        /// </summary>
        internal static string share_file {
            get {
                return ResourceManager.GetString("share_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storeg Code.
        /// </summary>
        internal static string StoregCode {
            get {
                return ResourceManager.GetString("StoregCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful.
        /// </summary>
        internal static string successful {
            get {
                return ResourceManager.GetString("successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings have been saved successfully!.
        /// </summary>
        internal static string succsave {
            get {
                return ResourceManager.GetString("succsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Counting.
        /// </summary>
        internal static string upload_counting {
            get {
                return ResourceManager.GetString("upload_counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User number.
        /// </summary>
        internal static string user_number {
            get {
                return ResourceManager.GetString("user_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id cannot be found.
        /// </summary>
        internal static string UserIdcannotbefound {
            get {
                return ResourceManager.GetString("UserIdcannotbefound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WA/AG/A Info.
        /// </summary>
        internal static string WaAgAInfo {
            get {
                return ResourceManager.GetString("WaAgAInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WA/ operation:.
        /// </summary>
        internal static string WAoperation {
            get {
                return ResourceManager.GetString("WAoperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with error:.
        /// </summary>
        internal static string with_Error {
            get {
                return ResourceManager.GetString("with_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace:.
        /// </summary>
        internal static string Workplace {
            get {
                return ResourceManager.GetString("Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
